name: "Hello Actions"
description: "Greet someone"
author: "octocate@github.com"

inputs:
   MY-NAME:
      description: "Who to greet"
      required: true 
      default: "World"
  
runs:
  using: "docker"
  image: "Dockerfile"
   
branding:
  icon: "mic"
  color: "purple"
    

    










